name: Build, push, and sign container target
description: Reusable step that builds a target, pushes it, and signs the resulting digest.
inputs:
  image_name:
    description: Container image name (repository)
    required: true
  registry_path:
    description: Full registry path (e.g. ghcr.io/OWNER)
    required: true
  tags:
    description: Space-separated tags (without SHA)
    required: true
  target:
    description: Build target
    required: true
runs:
  using: "composite"
  steps:
    - name: Build image (${{ inputs.target }})
    # buildah-build supports caching within same runner between steps
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.image_name }}
        containerfiles: |
          ./Containerfile
        tags: ${{ inputs.tags }} ${{ github.sha }}
        extra-args: |
          --target ${{ inputs.target }}
        # layers: true  # uncomment if you want layer caching behavior enabled explicitly

    - name: Determine Upstream Image Version
      shell: bash
      run: |
        version=$(podman image inspect $IMAGE \
          --format '{{ index .Config.Labels "org.opencontainers.image.version" }}')
        echo "IMAGE_VERSION=$version" >> $GITHUB_ENV
      env:
        IMAGE: ${{ steps.build_image.outputs.image-with-tag }}

    - name: Tag local image
      shell: bash
      run: |
        set -x
        LONG_TAG="${{ inputs.target }}-${IMAGE_VERSION}"
        MAJOR_TAG=$(echo ${LONG_TAG} | sed 's:\..*::')
        podman tag ${IMAGE} ${{ inputs.image_name }}:${LONG_TAG} ${{ inputs.image_name }}:${MAJOR_TAG}
        podman images
      env:
        IMAGE: ${{ steps.build_image.outputs.image-with-tag }}
        IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

    - name: Push to registry (${{ inputs.target }})
      id: push_image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: |
          ${{ steps.build_image.outputs.tags }}
          ${{ inputs.target }}-${{ env.IMAGE_VERSION }}
        registry: ${{ inputs.registry_path }}

    - name: Sign image (${{ inputs.target }})
      shell: bash
      env:
        DIGEST: ${{ steps.push_image.outputs.digest }}
        COSIGN_PRIVATE_KEY: ${{ env.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ env.COSIGN_PASSWORD }}
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY \
          ${{ inputs.registry_path }}/${{ inputs.image_name }}@${DIGEST}
