name: build
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kinoite

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (opa)
        id: build-image-opa
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: opa-stable opa-42 ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          extra-args: |
            --target opa

      - name: Push to GitHub Container Repository (opa)
        id: push-to-ghcr-opa
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image-opa.outputs.image }}
          tags: ${{ steps.build-image-opa.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ github.actor }}

      - name: Sign container image (opa)
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}@${TAGS}
        env:
          TAGS: ${{ steps.push-to-ghcr-opa.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Build image (julia)
        id: build-image-julia
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: julia-stable julia-42 ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          extra-args: |
            --target julia

      - name: Push to GitHub Container Repository (julia)
        id: push-to-ghcr-julia
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image-julia.outputs.image }}
          tags: ${{ steps.build-image-julia.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ github.actor }}

      - name: Sign container image (julia)
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}@${TAGS}
        env:
          TAGS: ${{ steps.push-to-ghcr-julia.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
