name: build
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kinoite

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push/Sign (opa)
        uses: ./.github/actions/build-push-sign
        with:
          image_name: ${{ env.IMAGE_NAME }}
          registry_path: ${{ env.REGISTRY }}/${{ github.actor }}
          tags: "opa-stable opa-42"
          target: "opa"

      - name: Build/Push/Sign (julia)
        uses: ./.github/actions/build-push-sign
        with:
          image_name: ${{ env.IMAGE_NAME }}
          registry_path: ${{ env.REGISTRY }}/${{ github.actor }}
          tags: "julia-stable julia-42"
          target: "julia"
